version: 1.0.{build}
configuration:
  - Debug
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal